"""add_expires_at_to_matlab_instances

Revision ID: 4e143e556955
Revises: 7d788f840ec1
Create Date: 2023-04-18 17:17:02.372463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4e143e556955"
down_revision = "7d788f840ec1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "matlab_instances", sa.Column("expires_at", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("matlab_instances", "expires_at")
    # ### end Alembic commands ###
