"""add super user

Revision ID: 03a5f76375ee
Revises: 07c71f4389b6
Create Date: 2023-04-11 11:14:20.679395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "03a5f76375ee"
down_revision = "07c71f4389b6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_model", sa.Column("is_superuser", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_model", "is_superuser")
    # ### end Alembic commands ###
